AllCops:
  Exclude:
    - db/**/*
    - config.ru
    - bin/**/*

# In this project we sometimes still use the old hash syntax (:key => "value")
HashSyntax:
  Enabled: false

# Following this cop sometimes makes things harder to read
IfUnlessModifier:
  Enabled: false

Style/SymbolProc:
  Exclude:
    # Enabling the cop make the factories less readable.
    - 'spec/factories.rb'

# Temporarily disabled.
#
# These cops will generate noisy diffs when they are run with --auto-correct,
# so we don't want them turned on for files with a lot of violations. They
# are still active for other files.

Style/BlockEndNewline:
  Exclude:
    - 'spec/presenters/mainstream_browse_page_presenter_spec.rb'

Style/ClosingParenthesisIndentation:
  Exclude:
    - 'app/services/draft_tag_remover.rb'
    - 'spec/notifiers/publishing_api_notifier_spec.rb'
    - 'spec/presenters/mainstream_browse_page_presenter_spec.rb'
    - 'spec/presenters/tag_presenter_spec.rb'

Style/FirstParameterIndentation:
  Exclude:
    - 'spec/presenters/groups_presenter_spec.rb'

Style/MultilineBlockLayout:
  Exclude:
    - 'spec/presenters/mainstream_browse_page_presenter_spec.rb'

Style/SpaceAroundOperators:
  Exclude:
    - 'spec/services/list_publisher_spec.rb'

Style/SpaceInsideBrackets:
  Exclude:
    - 'spec/models/tagged_documents_spec.rb'

Style/SpaceInsideParens:
  Exclude:
    - 'spec/features/listing_browse_pages_spec.rb'
