default: &default
  adapter: mysql2
  encoding: utf8
  username: collections_pub
  password: collections_publisher
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>

development:
  <<: *default
  database: collections_publisher_development

test: &test
  <<: *default
  database: collections_publisher_test

cucumber:
  <<: *test
