default: &default
  adapter: mysql2
  encoding: utf8
  username: collections_pub
  password: collections_publisher

development:
  <<: *default
  database: collections_publisher_development
  url: <%= ENV["DATABASE_URL"]%>

test: &test
  <<: *default
  database: collections_publisher_test
  url: <%= ENV["TEST_DATABASE_URL"] %>
production:
  <<: *default

cucumber:
  <<: *test
