name: CI

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths-ignore:
      - "Jenkinsfile"
      - ".git**"
  pull_request:

jobs:
  security-analysis:
    name: Security Analysis
    uses: alphagov/govuk-infrastructure/.github/workflows/brakeman.yml@main

  lint-scss:
    name: Lint SCSS
    uses: alphagov/govuk-infrastructure/.github/workflows/stylelint.yml@main
    with:
      files: "app/assets/stylesheets/"

  lint-javascript:
    name: Lint JavaScript
    uses: alphagov/govuk-infrastructure/.github/workflows/standardx.yml@main
    with:
      files: "'app/assets/javascripts/**/*.js'"

  lint-ruby:
    name: Lint Ruby
    uses: alphagov/govuk-infrastructure/.github/workflows/rubocop.yml@main

  test-ruby:
    name: Test Ruby
    uses: ./.github/workflows/rspec.yml

